/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurarRouteImport } from './routes/configurar'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as InstrutorRouteImport } from './routes/instrutor'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as DiagnosticoRunIdRouteImport } from './routes/diagnostico.$runId'
import { Route as NegociacaoRunIdRouteImport } from './routes/negociacao.$runId'
import { Route as PreparacaoRunIdRouteImport } from './routes/preparacao.$runId'
import { Route as PropostaRunIdRouteImport } from './routes/proposta.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurarRoute = ConfigurarRouteImport.update({
  id: '/configurar',
  path: '/configurar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrutorRoute = InstrutorRouteImport.update({
  id: '/instrutor',
  path: '/instrutor',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRunIdRoute = DiagnosticoRunIdRouteImport.update({
  id: '/diagnostico/$runId',
  path: '/diagnostico/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociacaoRunIdRoute = NegociacaoRunIdRouteImport.update({
  id: '/negociacao/$runId',
  path: '/negociacao/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparacaoRunIdRoute = PreparacaoRunIdRouteImport.update({
  id: '/preparacao/$runId',
  path: '/preparacao/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaRunIdRoute = PropostaRunIdRouteImport.update({
  id: '/proposta/$runId',
  path: '/proposta/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configurar': typeof ConfigurarRoute
  '/historico': typeof HistoricoRoute
  '/impacto': typeof ImpactoRoute
  '/instrutor': typeof InstrutorRoute
  '/relatorio': typeof RelatorioRoute
  '/diagnostico/$runId': typeof DiagnosticoRunIdRoute
  '/negociacao/$runId': typeof NegociacaoRunIdRoute
  '/preparacao/$runId': typeof PreparacaoRunIdRoute
  '/proposta/$runId': typeof PropostaRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configurar': typeof ConfigurarRoute
  '/historico': typeof HistoricoRoute
  '/impacto': typeof ImpactoRoute
  '/instrutor': typeof InstrutorRoute
  '/relatorio': typeof RelatorioRoute
  '/diagnostico/$runId': typeof DiagnosticoRunIdRoute
  '/negociacao/$runId': typeof NegociacaoRunIdRoute
  '/preparacao/$runId': typeof PreparacaoRunIdRoute
  '/proposta/$runId': typeof PropostaRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configurar': typeof ConfigurarRoute
  '/historico': typeof HistoricoRoute
  '/impacto': typeof ImpactoRoute
  '/instrutor': typeof InstrutorRoute
  '/relatorio': typeof RelatorioRoute
  '/diagnostico/$runId': typeof DiagnosticoRunIdRoute
  '/negociacao/$runId': typeof NegociacaoRunIdRoute
  '/preparacao/$runId': typeof PreparacaoRunIdRoute
  '/proposta/$runId': typeof PropostaRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configurar'
    | '/historico'
    | '/impacto'
    | '/instrutor'
    | '/relatorio'
    | '/diagnostico/$runId'
    | '/negociacao/$runId'
    | '/preparacao/$runId'
    | '/proposta/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configurar'
    | '/historico'
    | '/impacto'
    | '/instrutor'
    | '/relatorio'
    | '/diagnostico/$runId'
    | '/negociacao/$runId'
    | '/preparacao/$runId'
    | '/proposta/$runId'
  id:
    | '__root__'
    | '/'
    | '/configurar'
    | '/historico'
    | '/impacto'
    | '/instrutor'
    | '/relatorio'
    | '/diagnostico/$runId'
    | '/negociacao/$runId'
    | '/preparacao/$runId'
    | '/proposta/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurarRoute: typeof ConfigurarRoute
  HistoricoRoute: typeof HistoricoRoute
  ImpactoRoute: typeof ImpactoRoute
  InstrutorRoute: typeof InstrutorRoute
  RelatorioRoute: typeof RelatorioRoute
  DiagnosticoRunIdRoute: typeof DiagnosticoRunIdRoute
  NegociacaoRunIdRoute: typeof NegociacaoRunIdRoute
  PreparacaoRunIdRoute: typeof PreparacaoRunIdRoute
  PropostaRunIdRoute: typeof PropostaRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurar': {
      id: '/configurar'
      path: '/configurar'
      fullPath: '/configurar'
      preLoaderRoute: typeof ConfigurarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrutor': {
      id: '/instrutor'
      path: '/instrutor'
      fullPath: '/instrutor'
      preLoaderRoute: typeof InstrutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/$runId': {
      id: '/diagnostico/$runId'
      path: '/diagnostico/$runId'
      fullPath: '/diagnostico/$runId'
      preLoaderRoute: typeof DiagnosticoRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negociacao/$runId': {
      id: '/negociacao/$runId'
      path: '/negociacao/$runId'
      fullPath: '/negociacao/$runId'
      preLoaderRoute: typeof NegociacaoRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparacao/$runId': {
      id: '/preparacao/$runId'
      path: '/preparacao/$runId'
      fullPath: '/preparacao/$runId'
      preLoaderRoute: typeof PreparacaoRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta/$runId': {
      id: '/proposta/$runId'
      path: '/proposta/$runId'
      fullPath: '/proposta/$runId'
      preLoaderRoute: typeof PropostaRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurarRoute: ConfigurarRoute,
  HistoricoRoute: HistoricoRoute,
  ImpactoRoute: ImpactoRoute,
  InstrutorRoute: InstrutorRoute,
  RelatorioRoute: RelatorioRoute,
  DiagnosticoRunIdRoute: DiagnosticoRunIdRoute,
  NegociacaoRunIdRoute: NegociacaoRunIdRoute,
  PreparacaoRunIdRoute: PreparacaoRunIdRoute,
  PropostaRunIdRoute: PropostaRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
